### ISSUE TITLE
SeqPrep truncating rather than merging

### ISSUE THREAD

**Issue by almitchell** [jstjohn/SeqPrep#43]
We are using SeqPrep as part of our analysis pipeline and have noticed some issues with the merging process. To demonstrate the issue, the following paired-end files each contain 1 sequence, 298 nucleotides long. The sequences overlap by 34 nucleotides.

I am running SeqPrep with the default parameters and without any adaptor trimming:

SeqPrep -f test_1.fastq -r test_2.fastq -1 unpaired_1.fastq.gz -2 unpaired_2.fastq.gz -s merged.fastq.gz

However, this does not merge the sequences: the merged.fastq.gz file is empty, but unpaired_1.fastq.gz and unpaired_2.fastq.gz each contain a single truncated sequence of 256 nucleotides (as in, 24 nucleotides that overlap actually get removed from the ends of the reads).

Any idea what might be the problem here? When I merge the same reads using FLASH, I get a single merged read of length 562 nucleotides (ie, the expected length if everything merged correctly). 

[test_1.fastq.gz](https://github.com/jstjohn/SeqPrep/files/1606099/test_1.fastq.gz)
[test_2.fastq.gz](https://github.com/jstjohn/SeqPrep/files/1606100/test_2.fastq.gz)

**Comment by jstjohn** [comment]
There is a setting for the minimum percent overlap to merge. Looks like it
is set at 15% which made sense for 100bp reads. You are looking at 11%
overlap so it wouldn’t be considered with default settings. You can drop
that down, maybe to the ceiling of ((15/298)*100) or so to have an
equivalent setting to what I typically use for 100bp reads.

The issue you are seeing with the truncation rather than merging is
interesting. Have you run the two reads through a paired sequence alignment
and inspected the results? It might be that they are from a repetitive
region and there are a few valid pairwise alignments between the reads?

**Comment by almitchell** [comment]
Thanks for getting back on this. Is the % of overlapping reads a command line argument? I tried the -o setting, but this seems correspond to the number of bases that overlap, not the overall %.

Re: truncation - I ran BLAST on the 2 sequences and they only seem to align at the overlapping regions.

**Comment by jstjohn** [comment]
This is going to give you problems: `SeqPrep/utils.h:#define MAX_SEQ_LEN (256)`

**Comment by jstjohn** [comment]
So do this change to `utils.h`, then do a `make clean && make`:

```
-#define MAX_SEQ_LEN (256)
+#define MAX_SEQ_LEN (1024)
```

**Comment by jstjohn** [comment]
Just confirmed that the above change gives you the expected merge on the test files you provided.

**Comment by jstjohn** [comment]
Feel free to open a PR w/ that change too

**Comment by almitchell** [comment]
That's great - problem solved. Thanks for your help.
